---
title: "GIS의 개념"
author: Sang-Il Lee
date-modified: last-modified
number-sections: true
format: 
  html: 
    toc: true
code-link: true
code-copy: true
lightbox: true
execute: 
  warning: false
  error: false
  freeze: auto
editor: visual
editor_options: 
  chunk_output_type: console
---

## GIS의 근원

## GIS의 정의

## GIS의 의미

### GIS의 G

GIS의 G는 GIS가 특별한 종류의 데이터를 다룬다는 것을 의미한다. 그 특별한 데이터는 지리적(geographic) 혹은 공간적(spatial) 혹은 지리공간적(geospatial) 데이터이다. 지리적 데이터는 비지리적 데이터와 달리 세 가지 요소를 반드시 갖추고 있어야 한다. 그 세가지는 위치(location), 속성(attributes), 공간관계(spatial relationships)이다.

필수 패키지를 불러온다.

```{r}
library(tidyverse)
library(sf)
library(tmap)
```

필수 셰이프 파일을 불러온다.

```{r}
#| results: hide
sigungu1 <- st_read("D:/My R/Korean Administrative Areas/행정구역 셰이프 파일/3 Generalization/2023_2Q/SIGUNGU1_2023_2Q_GEN_0030.shp", options = "ENCODING=CP949")
sido_polyline <- st_read("D:/My R/Korean Administrative Areas/행정구역 셰이프 파일/3 Generalization/2023_2Q/SIDO_Polyline_2023_2Q_GEN_0030.shp", options = "ENCODING=CP949")
bbox_ulleung <- st_read("D:/My R/Korean Administrative Areas/행정구역 셰이프 파일/3 Generalization/2023_2Q/BBOX_Ulleung_2023_2Q_GEN_0030.shp", options = "ENCODING=CP949")
bbox_seohae <- st_read("D:/My R/Korean Administrative Areas/행정구역 셰이프 파일/3 Generalization/2023_2Q/BBOX_Seohae3_2023_2Q_GEN_0030.shp", options = "ENCODING=CP949")
seoul_gu <- st_read(
  "D:/My R/Korean Administrative Areas/행정구역 셰이프 파일/2 Original Cleaning/2023_2Q/SEOUL_GU_2023_2Q.shp", options = "ENCODING=CP949"
  ) 
seoul_sido <- st_read(
  "D:/My R/Korean Administrative Areas/행정구역 셰이프 파일/2 Original Cleaning/2023_2Q/SEOUL_SIDO_2023_2Q.shp", options = "ENCODING=CP949"
  )
```

관악구가 표시된 시군구 지도를 제작한다.

```{r}
#| label: fig-gwanak-1
#| fig-cap: 시군구 지도 상의 관악구의 위치
gwanak_gu <- sigungu1 |> 
  filter(SGG1_NM == "관악구")
my_map <- tm_shape(sigungu1) + tm_polygons() +
  tm_shape(gwanak_gu) + tm_polygons(col = "#e41a1c") +
  tm_shape(sido_polyline) + tm_lines(col = "black", lwd = 1.5) +
  tm_shape(bbox_ulleung) + tm_lines() +
  tm_shape(bbox_seohae) + tm_lines() +
  tm_layout(inner.margins = c(0.02, 0.03, 0.02, 0.04)) +
  tm_scale_bar(breaks = seq(0, 200, 50), color.dark = "gray60", position = c(0.48, 0.01))
my_map
```

```{r}
#| echo: false
#| output: false
gwanak_gu <- sigungu1 |> 
  filter(SGG1_NM == "관악구")
my_map <- tm_shape(sigungu1) + tm_polygons(lwd = 1) +
  tm_shape(gwanak_gu) + tm_polygons(col = "#e41a1c") +
  tm_shape(sido_polyline) + tm_lines(col = "black", lwd = 2) +
  tm_shape(bbox_ulleung) + tm_lines() +
  tm_shape(bbox_seohae) + tm_lines() +
  tm_layout(inner.margins = c(0.04, 0.03, 0.02, 0.04)) +
  tm_scale_bar(breaks = seq(0, 200, 50), text.size = 0.5, color.dark = "gray60", position = c(0.52, 0.01)) +
  tm_credits(text = "SANG-IL LEE, Geography Education at SNU, 2024", size = 0.8, position = c(0.02, 0.01))
my_map
my.path.name <- "D:/My Classes/2024년 2학기/지리정보체계와 지리교육/이미지/"
my.file.name <- paste0(my.path.name, "관악구_시군구", ".jpg")
tmap_save(my_map, filename = my.file.name, height = 12.1, dpi = 600)
```

관악구가 표시된 서울시 지도를 제작한다.

```{r}
#| label: fig-gwanak-2
#| fig-cap: 서울시 지도 상의 관악구의 위치
gwanak_gu <- seoul_gu |> 
  filter(SGG1_NM == "관악구")
my_map <- tm_shape(seoul_gu) + tm_polygons() +
  tm_shape(gwanak_gu) + tm_borders(col = "#e41a1c", lwd = 3) + 
  tm_layout(inner.margins = c(0.06, 0.04, 0.04, 0.04)) + 
  tm_scale_bar(breaks = seq(0, 20, 4), color.dark = "gray60", position = c(0.03, 0.01))
my_map 
```

```{r}
#| echo: false
#| output: false
gwanak_gu <- seoul_gu |> 
  filter(SGG1_NM == "관악구")
my_map <- tm_shape(seoul_gu) + tm_polygons() +
  tm_shape(gwanak_gu) + tm_borders(col = "#e41a1c", lwd = 5) + 
  tm_layout(inner.margins = c(0.05, 0.04, 0.04, 0.04)) + 
  tm_scale_bar(breaks = seq(0, 20, 5), text.size = 0.6, color.dark = "gray60", position = c(0.03, 0.01)) +
  tm_credits(text = "SANG-IL LEE, Geography Education at SNU, 2024", size = 0.8, position = c(0.76, 0.01))
my_map 
my.path.name <- "D:/My Classes/2024년 2학기/지리정보체계와 지리교육/이미지/"
my.file.name <- paste0(my.path.name, "관악구_서울", ".jpg")
tmap_save(my_map, filename = my.file.name, height = 12.1, dpi = 600)
```

### GIS의 I

### GIS의 S

## GIS의 구성요소

## GIS의 역사

## GIS와 지리
