---
title: "측정"
author: Sang-Il Lee
date-modified: last-modified
number-sections: true
format: 
  html: 
    toc: true
code-link: true
code-copy: true
lightbox: true
execute: 
  warning: false
  error: false
  freeze: auto
editor: visual
editor_options: 
  chunk_output_type: console
---

## 준비

필수적인 패키지를 설치한다. 래스터 분석을 위한 기본 패키지를 `raster`를 사용한다.

```{r}
library(tidyverse)
library(terra)
library(sf)
library(tmap)
```

서울에 대한 SRTM 기반 DEM 데이터를 불러온다.

```{r}
dem_seoul <- rast("D:/My R/World Data Manupulation/USGS EarthExplorer/srtm_seoul.tif")
dem_seoul_mask <- rast("D:/My R/World Data Manupulation/USGS EarthExplorer/srtm_seoul_mask.tif")
```

서울의 행정구역 바운더리 파일을 불러온다.

```{r}
#| results: hide
seoul <- st_read("D:/My R/Korean Administrative Areas/행정구역 셰이프 파일/2 Original Cleaning/2023_2Q/SEOUL_SIDO_2023_2Q.shp")
seoul_gu <- st_read("D:/My R/Korean Administrative Areas/행정구역 셰이프 파일/2 Original Cleaning/2023_2Q/SEOUL_GU_2023_2Q.shp")
seoul_dong <- st_read("D:/My R/Korean Administrative Areas/행정구역 셰이프 파일/2 Original Cleaning/2023_2Q/SEOUL_EMD_2023_2Q.shp")
```

## 기본 원리

## 조널 지오메트리

### 면적

우선 서울구에 대한 래스터 레이어를 생성한다.

```{r}
seoul_gu_r <- rasterize(seoul_gu, dem_seoul_mask, field = "SGG1_CD")
```

구에 해당되는 셀에 해당 구의 면적을 할당하여 새로운 래이어를 생성한다. `cellSize()` 함수를 통해 모든 셀에 해당 셀의 면적이 들어가 있는 래스터를 생성한 후, `zonal()` 함수를 적용한다. `as.raster` 아규먼트를 통해 래스터 레이어를 생성하는 것이 키포인트이다.

```{r}
seoul_gu_area <- cellSize(seoul_gu_r)/1000000
seoul_gu_area_r <- zonal(seoul_gu_area, seoul_gu_r, fun = "sum", na.rm = TRUE, as.raster = TRUE)
```

지도를 제작한다.

```{r}
my_map <- tm_shape(seoul_gu_area_r, raster.downsample = FALSE) + 
  tm_raster(style = "cont", palette = "Purples", title = expression("Area(km"^2*")")) +
  # tm_shape(seoul_gu) + tm_borders(col = "gray80") +
  tm_shape(seoul) + tm_borders(col = "gray20", lwd = 1.5) +
  tm_legend(legend.position = c(0.85, 0.03), legend.bg.color = "white", legend.bg.alpha = 0.6) +
  tm_layout(inner.margins = c(0.07, 0.04, 0.06, 0.04), 
            title = "Measurement: Area", title.size = 1, 
            title.position = c("LEFT", "TOP")) + 
  tm_scale_bar(breaks = seq(0, 20, 4), color.dark = "gray60", position = c(0.03, 0.01))
my_map
```

```{r}
#| echo: false
#| output: false
my_map <- tm_shape(seoul_gu_area_r, raster.downsample = FALSE) + 
  tm_raster(style = "cont", palette = "Purples", title = expression("Area(km"^2*")")) +
  # tm_shape(seoul_gu) + tm_borders(col = "gray80") +
  tm_shape(seoul) + tm_borders(col = "black", lwd = 2) +
  tm_legend(legend.position = c(0.87, 0.05), legend.bg.color = "white", legend.bg.alpha = 0.6, legend.title.size = 1.5, legend.text.size = 1.2) +
  tm_layout(inner.margins = c(0.05, 0.04, 0.06, 0.04), 
            title = "Measurement: Area", title.size = 2,
            title.position = c(0.02, 0.97)) + 
  tm_scale_bar(breaks = seq(0, 20, 5), text.size = 0.6, color.dark = "gray60", position = c(0.03, 0.01)) +
  tm_credits(text = "SANG-IL LEE, Geography Education at SNU, 2024", size = 0.8, position = c(0.76, 0.01))
my_map
my.path.name <- "D:/My Classes/2024년 2학기/지리정보체계와 지리교육/이미지/"
my.file.name <- paste0(my.path.name, "래스터_3_면적", ".jpg")
tmap_save(my_map, filename = my.file.name, height = 12.1, dpi = 600)
```

### 주변길이

약간의 계산이 필요하다. 속도가 느리다. 성공은 했지만, 다른 방법이 있을 듯 하다.

```{r}

seoul_r <- rasterize(seoul, dem_seoul_mask, field = "SD_CD")

seoul_perimeter_r <- seoul_gu_r

region_ids <- unique(values(seoul_gu_r))
region_ids <- region_ids[!is.na(region_ids)]

for (region_id in region_ids) {
  region_r <- seoul_gu_r
  region_r[region_r != region_id] <- NA # 구별로 완전히 독립시킨다. 그래야만 boundaries() 함수가 제대로 작동
  region_boundary <- boundaries(region_r, classes = TRUE)
  perimeter_cells <- sum(values(region_boundary) == 1, na.rm = TRUE)
  cell_res <- res(seoul_gu_r)[1]  
  perimeter <- perimeter_cells * cell_res / 1000
  region_r_r <- seoul_gu_r == region_id # 값을 셀로 옮기려면 서울 전체가 살아있는 raster가 존재해야 함.
  seoul_perimeter_r[region_r_r] <- perimeter
}

```

지도를 제작한다.

```{r}
my_map <- tm_shape(seoul_perimeter_r, raster.downsample = FALSE) + 
  tm_raster(style = "cont", palette = "Purples", title = "Perimeter(km)") +
  # tm_shape(seoul_gu) + tm_borders(col = "gray80") +
  tm_shape(seoul) + tm_borders(col = "gray20", lwd = 1.5) +
  tm_legend(legend.position = c(0.85, 0.02), legend.bg.color = "white", legend.bg.alpha = 0.6) +
  tm_layout(inner.margins = c(0.07, 0.04, 0.06, 0.04), 
            title = "Measurement: Perimeter", title.size = 1, 
            title.position = c("LEFT", "TOP")) + 
  tm_scale_bar(breaks = seq(0, 20, 4), color.dark = "gray60", position = c(0.03, 0.01))
my_map
```

```{r}
#| echo: false
#| output: false
my_map <- tm_shape(seoul_perimeter_r, raster.downsample = FALSE) + 
  tm_raster(style = "cont", palette = "Purples", title = "Perimeter(km)") +
  # tm_shape(seoul_gu) + tm_borders(col = "gray80") +
  tm_shape(seoul) + tm_borders(col = "black", lwd = 2) +
  tm_legend(legend.position = c(0.87, 0.03), legend.bg.color = "white", legend.bg.alpha = 0.6, legend.title.size = 1.5, legend.text.size = 1.2) +
  tm_layout(inner.margins = c(0.05, 0.04, 0.06, 0.04), 
            title = "Measurement: Perimeter", title.size = 2,
            title.position = c(0.02, 0.97)) + 
  tm_scale_bar(breaks = seq(0, 20, 5), text.size = 0.6, color.dark = "gray60", position = c(0.03, 0.01)) +
  tm_credits(text = "SANG-IL LEE, Geography Education at SNU, 2024", size = 0.8, position = c(0.76, 0.01))
my_map
my.path.name <- "D:/My Classes/2024년 2학기/지리정보체계와 지리교육/이미지/"
my.file.name <- paste0(my.path.name, "래스터_3_주변", ".jpg")
tmap_save(my_map, filename = my.file.name, height = 12.1, dpi = 600)
```
