---
title: "공간데이터모델"
author: Sang-Il Lee
date-modified: last-modified
number-sections: true
format: 
  html: 
    toc: true
code-link: true
code-copy: true
lightbox: true
execute: 
  warning: false
  error: false
  freeze: auto
editor: visual
editor_options: 
  chunk_output_type: console
---

## 정의와 개념

## 개념적 모델

### 객체-기반 모델

### 필드-기반 모델

## 논리적 모델

### 벡터 모델

#### 개요

피처 클래스(feature class)에 대한 개념적 설명

필수 패키지를 설치한다.

```{r}
library(tidyverse)
library(sf)
library(tmap)
library(readxl)
```

포인트 레이어로서 서울시 역 위치에 대한 셰이프 파일을 생성한다.

```{r}
seoul <- st_read("D:/My R/Korean Administrative Areas/행정구역 셰이프 파일/2 Original Cleaning/2023_2Q/SEOUL_SIDO_2023_2Q.shp")
seoul_subst_coords <- read_excel("D:/My R/GIS/서울시 역사마스터 정보.xlsx") 
seoul_subst <- st_as_sf(seoul_subst_coords, coords = c("위도", "경도"), crs = 4326)
seoul_subst <- seoul_subst |> 
  st_transform(crs = st_crs(seoul)) |> 
  st_intersection(seoul)
```

라인 레이어로서 서울시 도로망에 대한 셰이프 파일을 불러온다.

```{r}
#| results: hide
seoul_sn <- st_read("D:/My R/Vector Data Manipulation Korea/Korea_Transport_Database/seoul_link.shp", options = "ENCODING=CP949")
```

폴리곤 레이어로서 서울시 구 경계 셰이프 파일을 불러온다.

```{r}
#| results: hide
seoul_gu <- st_read("D:/My R/Korean Administrative Areas/행정구역 셰이프 파일/2 Original Cleaning/2023_2Q/SEOUL_GU_2023_2Q.shp")
```

세 개의 레이어를 합쳐 지도를 생성한다.

```{r}
#| label: fig-feature_class
#| fig-cap: 피처 클래스
tm_shape(seoul) + tm_polygons(col = "gray98") +
  tm_shape(seoul_sn) + tm_lines(col = "gray70") +
  tm_shape(seoul_gu, is.master = TRUE) + tm_borders(lwd = 2) +
  tm_shape(seoul_subst) + tm_symbols(col = "black", size = 0.2) +
  tm_layout(inner.margins = c(0.06, 0.04, 0.04, 0.04)) + 
  tm_scale_bar(breaks = seq(0, 20, 4), color.dark = "gray60", position = c(0.03, 0.01))
```

```{r}
#| echo: false
#| output: false
my_map <- tm_shape(seoul) + tm_polygons(col = "gray98") +
  tm_shape(seoul_sn) + tm_lines(col = "gray70") +
  tm_shape(seoul_gu, is.master = TRUE) + tm_borders(lwd = 2, col = "gray20") +
  tm_shape(seoul_subst) + tm_symbols(col = "black", size = 0.3) +
  tm_layout(inner.margins = c(0.05, 0.04, 0.04, 0.04), title = "Feature Classes", title.size = 2, title.position = c(0.02, 0.97)) + 
  tm_scale_bar(breaks = seq(0, 20, 5), text.size = 0.6, color.dark = "gray60", position = c(0.03, 0.01)) +
  tm_credits(text = "SANG-IL LEE, Geography Education at SNU, 2024", size = 0.8, position = c(0.76, 0.01))
my_map 
my.path.name <- "D:/My Classes/2024년 2학기/지리정보체계와 지리교육/이미지/"
my.file.name <- paste0(my.path.name, "피처 클래스", ".jpg")
tmap_save(my_map, filename = my.file.name, height = 12.1, dpi = 600)
```

#### 구현

#### 물리적 모델

### 래스터 모델

#### 개요

#### 구현

#### 물리적 모델
